galaxyproject/pulsar

pulsar/client/transport/curl.py

Only implemented in the curl transport though.
Client changes in Galaxy in galaxyproject/galaxy#227

Support for resuming staging transfers

---

app.yml.sample
pulsar/client/amqp_exchange.py
pulsar/client/amqp_exchange_factory.py
pulsar/client/manager.py
pulsar/client/util.py
pulsar/messaging/bind_amqp.py

Ensure AMQP consumers receive published messages

---

pulsar/client/amqp_exchange.py

If an AMQP endpoint was consuming more than one queue (e.g. Galaxy), acknowledgement retries could be sent on the wrong queue.
Also, only start one acknowledgement manager thread, rather than one per consumer.

Resubmit messages to the right queue

---

pulsar/client/action_mapper.py

Closing out old doc bug

---

pulsar/client/util.py

Here's the problem I'm trying to fix:
https://gist.github.com/natefoo/176be081602970166395772cc48e11e3
It may be the wrong way to fix it, but it does seem to be working on Test/Main.

Ensure destination directories exist when copying files

---

.travis.yml
Makefile
install_test/test_install.bash
tox.ini

Finally includes testing against actual Galaxy master branch.

Add install testing to Travis.

---

pulsar/managers/queued_external_drmaa.py

Fix type error in external drmaa.

---

.travis/setup_tests.sh
pulsar/core.py
pulsar/scripts/chown_working_directory.py
test/test_utils.py

Also, fix handling `conda_*` app config params and don't init conda with each test app launch.

Fix more tests

---

pulsar/client/amqp_exchange.py

This module and all the AMQP acknowledgement stuff is a big mess and needs to be cleaned up... But this works for now.
Fixes #142

Attempt to handle failures in reading AMQP republish contents

---

HISTORY.rst
Makefile
docs/developing.rst
docs/pulsar.cache.rst
docs/pulsar.client.rst
docs/pulsar.client.staging.rst
docs/pulsar.client.test.rst
docs/pulsar.client.transport.rst
docs/pulsar.managers.base.rst
docs/pulsar.managers.rst
docs/pulsar.managers.staging.rst
docs/pulsar.managers.util.cli.job.rst
docs/pulsar.managers.util.cli.rst
docs/pulsar.managers.util.cli.shell.rst
docs/pulsar.managers.util.condor.rst
docs/pulsar.managers.util.drmaa.rst
docs/pulsar.managers.util.job_script.rst
docs/pulsar.managers.util.rst
docs/pulsar.mesos.rst
docs/pulsar.messaging.rst
docs/pulsar.rst
docs/pulsar.scripts.rst
docs/pulsar.tools.rst
docs/pulsar.util.pastescript.rst
docs/pulsar.util.rst
docs/pulsar.web.rst
pulsar/__init__.py

My first time releasing so I figured I'd PR it for review.

Release 0.8.0

---

pulsar/main.py
scripts/pulsar

Unless uwsgi is available - but I can't get that to work at all today.

Fix Pulsar configs so ./run.sh just works out of the box.

---

pulsar/manager_endpoint_util.py

This is the pulsar half of a fix for #150.

Pass full job status for failed and lost jobs.

---

docs/install.rst
pulsar/main.py
test/test_utils.py

xref: https://github.com/galaxyproject/galaxy/issues/6426

Added support for overriding config through environment variables

---

test/client_staging_test.py
test/test_utils.py

See https://docs.python.org/2/library/unittest.html#deprecated-aliases

Fix deprecated ``assertEquals()``

---

pulsar/managers/stateful.py

Bad merge of really old branch?

Fix a method missing problem.

---

app.yml.sample

(from 'amqp_republish_time' which is unused)
xref https://github.com/galaxyproject/galaxy/pull/7983

Fix 'amqp_ack_republish_time' in sample

---

docs/files/job_conf_sample_mq_rsync.xml

Param "url" should be "amqp_url"

Updated amqp_url in job_conf_sample_mq_rsync.xml

---

.gitignore
Makefile
docker/coexecutor/Dockerfile
docs/files/file_actions_sample_1.yaml
pulsar/client/__init__.py
pulsar/client/action_mapper.py
pulsar/client/client.py
pulsar/client/path_mapper.py
pulsar/client/staging/__init__.py
pulsar/client/staging/down.py
pulsar/client/staging/up.py
pulsar/client/test/check.py
pulsar/core.py
pulsar/managers/stateful.py
test/action_mapper_test.py
test/client_staging_test.py
test/path_mapper_test.py

Client should be able to say "stage this file from the object id" instead of saying "stage this path".

Refactor toward passing objectstore identifying information around.

---

docker/coexecutor/Makefile
pulsar/client/client.py
pulsar/main.py
pulsar/scripts/mesos_framework.py

- Enable logging and make configurable.
- Bump version to 0.12.0.
- Improve error message if pykube isn't installed.

Improvements to Kubernetes pod execution stuff.

---

pulsar/client/action_mapper.py
pulsar/client/staging/__init__.py
pulsar/core.py
pulsar/managers/__init__.py
pulsar/managers/base/__init__.py
pulsar/managers/staging/pre.py
pulsar/managers/stateful.py
test/persistence_test.py
test/test_utils.py
test/transfer_action_test.py

More general information than just path was passed through layers above this in #180, this pushes that information down a layer... the idea is to add an object store reference here for remote staging of data directly from an object store.

Refactor file action to push source into action class.

---

pulsar/client/client.py

- Configure container dependency resolution in the client based on Conda installed in the Docker image.
- Choose manager_type based on whether there is container configured or not, this way this doesn't need to be dispatched upon in the client.
This should allow me to create just a single Kubernetes Pulsar runner in Galaxy that does the right thing (two-containers vs one-container) based on whether docker is enabled for the runner and based on ``dependency_resolution`` job destination parameter.

Easier Kubernetes configuration.

---

pulsar/client/client.py
pulsar/client/setup_handler.py
pulsar/client/staging/up.py

Galaxy side that needs to be paired down to just use this (https://github.com/jmchilton/galaxy/commit/9ce25fedb10384ac5f3cceb366393e5fa6578855).

Parse assign_ids from job destination for Galaxy-side setup.

---

.travis/setup_tests.sh
pulsar/client/client.py
pulsar/client/staging/__init__.py
pulsar/client/staging/up.py
pulsar/managers/util/pykube_util.py

Requires matching Galaxy PR (will open soon) but seems to work on "developer laptop" 😅

Request and register ports for ITs.

---

.travis.yml
.travis/setup_tests.sh
setup.py
tox.ini

* removing py26 from setup.py
* migrating travis to use the xenial image
* adding tests for py36 and py37

drop python 2.6 and add 3.7 and update the testing infrastructure to a more recent Ubuntu setup

---

pulsar/client/client.py

Marius van den Beek @mvdbeek 11:06
> Before replicating all this between Galaxy and pulsar in slightly different ways it might be a good idea to converge this in pulsar, and maybe make all of this templateable ?
Longer term ofc
Nuwan Goonasekera @nuwang 11:11
> Yes, that would be good. There was a preliminary attempt at this which was abandoned pending the shift to Pulsar, but perhaps the template etc. can still be used? galaxyproject/galaxy#10714
Nate Coraor @natefoo 11:21
> pfft copy paste is the best method ;D
Nate Coraor @natefoo 11:29
> (yes, you're right, but if this works I'm PRing it anyway as I need it to work in production and we can refactor it later)

Set resource limits and walltime for k8s coexecution pods

---

pulsar/client/client.py

This was probably supposed to be part of https://github.com/galaxyproject/pulsar/commit/44e3b611c39cf39aed53ba2983f055127a9e3caa.

Expose file_actions via job destination parameters.

---

docs/developing.rst
pulsar/client/staging/up.py

Pulsar side of a fix for https://github.com/galaxyproject/galaxy/issues/12256 - I think the only thing that would need to happen Galaxy side is a version upgrade of the pulsar-galaxy-lib post release of this fix.

Fix Galaxy composite input references.

---

.github/workflows/galaxy_framework.yaml

I was trying to parameterize job conf based on branch and I didn't see how this would work without this.

Is this needed for branching to work?

---

.github/workflows/galaxy_framework.yaml
tools/replace_galaxy_requirements_for_ci.py

I think the other version didn't work properly #275.

Another attempt at replacing Galaxy's pulsar wheel for CI

---

pulsar/client/staging/down.py

Fixes https://github.com/galaxyproject/pulsar/issues/285

Enable globbed from_work_dir outputs for remote metadata

---

pulsar/client/test/check.py
pulsar/managers/unqueued.py
pytest.ini
requirements.txt
tox.ini

Similar to https://github.com/galaxyproject/galaxy/pull/13011 and will solve https://github.com/galaxyproject/galaxy/pull/13011/files#diff-3f0aa0fbd44b2692f0be1126a44fa3e5927dc134504baab708f2543f188e0e34R49-R50

Don't pass all environment variables to jobs launched by `Manager`

---

pulsar/client/action_mapper.py

May or may not fix https://github.com/galaxyproject/galaxy/issues/14212, but this is the right thing to do.

Use urlencode to encode path

---

pulsar/client/client.py

Support the k8s_job_ttl_secs_after_finished option as in the Galaxy Kubernetes runner

---

pulsar/manager_factory.py
pulsar/managers/staging/post.py

Fix recovering "lost" jobs where the job directory does not exist at startup/recovery time

---

pulsar/client/client.py
pulsar/client/job_directory.py
pulsar/managers/base/directory.py
pulsar/managers/util/job_script/DEFAULT_JOB_FILE_TEMPLATE.sh
pulsar/managers/util/job_script/__init__.py
pulsar/managers/util/pykube_util.py

Home directory verified to exist in https://github.com/galaxyproject/pulsar/pull/292/files but Galaxy's tests has a stronger condition on where it is created and it caught a regression that resulted in Pulsar writing the HOME directory into the working directory instead of the job directory.
xref https://github.com/galaxyproject/galaxy/pull/14743

Fixup pulsar lib 0.14.14

---

pulsar/client/client.py
pulsar/managers/util/pykube_util.py

Kubernetes stuff was broken in #303 - just return the relevant code to a state before that PR while I setup testing infrastructure for 0.15.0.

Revert kube changes

---

pulsar/client/action_mapper.py

Last Galaxy error I think.
Fixes error with https://github.com/galaxyproject/galaxy/pull/14748

Fix https://github.com/galaxyproject/pulsar/pull/299.

---

pulsar/managers/util/job_script/MEMORY_STATEMENT_TEMPLATE.sh

From galaxyproject/galaxy#11808 and galaxyproject/galaxy#8451.

Cluster memory statement changes from Galaxy

---

.github/workflows/pulsar.yaml
dev-requirements.txt
pulsar/client/test/check.py
test/client_transport_test.py
test/test_utils.py

Goal is eventually a Docker container -> GitHub Actions Service -> Finally Testable TES/K8S clients.

Load JobFilesApp from new external dependency.

---

pulsar/client/amqp_exchange.py

This should fix https://github.com/galaxyproject/pulsar/issues/328. @astalosj @mira-miracoli are you able to test this ?

Also try recovering from ConnectionResetError

---

.readthedocs.yaml
docs/requirements.txt

This is required as of September. Stolen from bioblend, thanks @nsoranzo :grin:

Add .readthedocs.yaml

---

pulsar/client/amqp_exchange.py
pulsar/client/transport/standard.py

socket.timeout is an alias for TimeoutError on python >= 3.10

Add explicit TimeoutError catching

---

HISTORY.rst
pulsar/__init__.py
pulsar/client/action_mapper.py
pulsar/client/transport/tus.py
requirements.txt
test/client_transport_test.py

Should allow Pulsar to target TUS endpoints added with https://github.com/galaxyproject/galaxy/pull/17242.

Implement tus uploads in Pulsar client.

---

dev-requirements.txt

xref: https://github.com/galaxyproject/galaxy/commit/c6aa4713be48d902231ca5bf5472f3660376a22f
thanks @nsoranzo!

Replace obsolete package types-pkg-resources with types-setuptools

---

pulsar/managers/base/directory.py
pulsar/managers/util/job_script/DEFAULT_JOB_FILE_TEMPLATE.sh
pulsar/managers/util/job_script/__init__.py

Galaxy side is in https://github.com/galaxyproject/galaxy/pull/16696

Prepare dirs from Galaxy, to properly recover resubmitted jobs

---

.github/workflows/deploy.yaml
.github/workflows/pulsar.yaml
MANIFEST.in
Makefile
dev-requirements.txt
setup.cfg
tox.ini

Will need [trusted publishing](https://docs.pypi.org/trusted-publishers/adding-a-publisher/) to be enabled on the 2 PyPI projects.

Add a deploy CI workflow

---

.github/workflows/galaxy_framework.yaml
pulsar/client/staging/down.py

A nice tweak for the xml language, and a requirement for creating directories via the yml language

Support collecting dirs via ``from_work_dir``
