galaxyproject/pulsar

pulsar/scripts/config.py

Otherwise, was getting the following error:
```
$ pulsar-config --supervisor --wsgi_server uwsgi --libdrmaa_path /usr/lib/slurm-drmaa/lib/libdrmaa.so --install
Bootstrapping pulsar configuration into directory .
Traceback (most recent call last):
File "/mnt/p3/.venv/bin/pulsar-config", line 9, in <module>
load_entry_point('pulsar-app==0.5.0', 'console_scripts', 'pulsar-config')()
File "/mnt/p3/.venv/local/lib/python2.7/site-packages/pulsar/scripts/config.py", line 207, in main
_handle_install(args, dependencies)
File "/mnt/p3/.venv/local/lib/python2.7/site-packages/pulsar/scripts/config.py", line 340, in _handle_install
pip.main("install", *dependencies)
TypeError: main() takes at most 1 argument (4 given)
```

Fix pip dependency installation

---

pulsar/managers/queued_drmaa_xsede.py

XSEDE would like us to run their job/user accounting script after submission.
TODO: A generalized callback framework for executing things at various points in the job lifecycle.

Add a job manager for XSEDE jobs

---

docs/galaxy_conf.rst

Small typo fix: `context` instead of `contxt`

Small typo fix

---

docs/files/job_conf_sample_remote_cluster.xml

Added the slash for the self-closed plugin pulsar tag in the file `job_conf_sample_remote_cluster.xml` located in `docs/files/`, otherwise we get the Exception:
```
Exception: Problem parsing the XML in file /Users/marenc01/Dev/galaxy/config/job_conf.xml, please correct the indicated portion of the file and restart Galaxy.mismatched tag: line 6, column 6
```
When running Galaxy.

Added the slash for the self-closed plugin pulsar tag

---

pulsar/client/amqp_exchange.py

Otherwise, if retry options are enabled, you get this:
```pytb
galaxy.jobs.runners.pulsar ERROR 2015-09-11 09:59:04,994 failure running job 433893
Traceback (most recent call last):
File "/galaxy-repl/instances/test/server/lib/galaxy/jobs/runners/pulsar.py", line 224, in queue_job
job_id = pulsar_submit_job(client, client_job_description, remote_job_config)
File "/galaxy-repl/instances/test/server/lib/pulsar/client/staging/up.py", line 43, in submit_job
client.launch(**launch_kwds)
File "/galaxy-repl/instances/test/server/lib/pulsar/client/client.py", line 314, in launch
response = self.client_manager.exchange.publish("setup", launch_params)
File "/galaxy-repl/instances/test/server/lib/pulsar/client/amqp_exchange.py", line 198, in publish
publish_kwds = …
```

Fix deepcopy() error with copying the errback method from PulsarExchange.

---

pulsar/scripts/config.py

config.py was failing on Windows due to missing attributes in the PlatformArgumentParser. As these are skipped for Windows, I just added a check so it doesn't try to access them on Windows.
With these little changes, pulsar-config worked for me on Windows. 
This fix is the least intrusive IMO, but I think a better solution would be to use hasattr, but I don't know if that would break any assumption by the rest of the code.

Fix config.py on Windows.

---

pulsar/managers/base/__init__.py
pulsar/managers/util/job_script/CLUSTER_SLOTS_STATEMENT.sh

Not sure why embedded Pulsar encounters the first issue (attempting to create the "remote" job dir after having already created it to stage inputs) when standalone Pulsar does not, but this fix should be harmless.
And update cluster slot handling as in galaxyproject/galaxy#1347.
Might not want to merge this yet as more may be discovered.

Fixes for things encountered when running jobs on Jetstream

---

pulsar/managers/util/drmaa/__init__.py

Only one active DRMAA session is possible per process. This allows multiple Galaxy runner plugins to be active in the same handler if Pulsar is being used as an embedded runner (they all have to target the same DRMAA library, however). Also add locking to calls that modify the number of active jobs, as per the Python-drmaa documentation.
See also galaxyproject/galaxy#2102

Use a global DRMAA session

---

pulsar/managers/util/cli/job/torque.py

Without this commit only very short jobs completed successfully, because the
status was always set to complete. This was because the status returned by
qstat contains leading spaces before the `job_state = Q` part, so I'm adding a
`.strip()`.

Fix PBS status reporting

---

pulsar/managers/queued_cli.py
pulsar/managers/staging/post.py
pulsar/managers/stateful.py

Previously jobs that failed to submit (bad resource requests, malformed
scripts, no qsub available, staging problems) would remain in waiting status
until pulsar was restarted.
Let me know if there is a better way to do this @jmchilton

Fail jobs that error during job submission

---

pulsar/managers/util/cli/__init__.py
pulsar/managers/util/job_script/CLUSTER_SLOTS_STATEMENT.sh
pulsar/managers/util/job_script/DEFAULT_JOB_FILE_TEMPLATE.sh
pulsar/managers/util/job_script/__init__.py

and update the job templates (just copied over from galaxy).
I feel that f539af2 is a terrible hack, suggestions for improvement welcome.
It does fix 
```
serving on http://127.0.0.1:8913
2016-04-12 14:59:30,536 DEBUG [pulsar.managers.base][[manager=_default_]-[action=preprocess]-[job=33]] job_id: 33 - Checking authorization of command_line [printenv > "/lustrework/vandenbeek/pulsar/pulsar-master/files/staging/33/outputs/dataset_33.dat"]
2016-04-12 14:59:30,537 ERROR [pulsar.managers.stateful][[manager=_default_]-[action=preprocess]-[job=33]] Failed job preprocess for 33:
Traceback (most recent call last):
File "/Users/marius/.venv/lib/python2.7/site-packages/pulsar/managers/stateful.py", line 79, in do_preprocess
self._proxied_manager.launch(job_id, *args, **kwargs)
File …
```

Fix for locating cli shell/job plugins

---

pulsar/client/interface.py

This way there is no discrepancy between the arguments that message queue pulsar and http pulsar consume.

Use managers defined in job destination parameters

---

pulsar/client/__init__.py
pulsar/client/exceptions.py
pulsar/client/manager.py
pulsar/client/transport/__init__.py
pulsar/client/transport/curl.py
pulsar/client/transport/standard.py

Allow the curl client transport to have a timeout value set (includes a general framework for setting any other transport options that might be necessary), and add an exception that can be raised up to the pulsar runner in Galaxy to handle communication problems while checking state
or submitting jobs.
Fixes a problem encountered on usegalaxy.org where the monitor thread would encounter some network problem and block forever (until handler restart).
Partially fixes #114 in that restarts will not kill running jobs, but if Galaxy attempts to submit a job while Pulsar is down it will still fail.
The Galaxy side looks like this, with a new `<param id="transport_timeout>` on `PulsarRESTJobRunner` plugins:
```diff
diff --git a/lib/galaxy/jobs/runners/pulsar.py …
```

curl transport improvements (timeout handling)

---

pulsar/managers/stateful.py

Tweak to behavior added here https://github.com/galaxyproject/pulsar/commit/8242741ba15e5b753fbd7f2845156552071adfa0. Don't postprocess the failed job, just indicate the proxy status as failed and be done with it.

Avoid loop when preprocessing fails and polling enabled.

---

dependency_resolvers_conf.xml.sample
pulsar/core.py

Using the previous version caused the error below; and pulsar failed to start. Applying the patch made it possible for pulsar to start and auto resolve dependencies.
Note: In addition i needed a dependency_resolvers_conf.xml in the pulsar folder containing
```<conda auto_install="True" auto_init="True"/>```
```
> Sourcing file ./local_env.sh
Starting pulsar with command [uwsgi --ini-paste "./server.ini" ""]
[uWSGI] getting INI configuration from ./server.ini
Starting uWSGI 2.0.15 (64bit) on [Fri May 12 14:01:37 2017]
compiled with version: 6.3.0 20170425 on 12 May 2017 13:17:07
os: Linux-4.9.0-2-amd64 #1 SMP Debian 4.9.18-1 (2017-03-30)
nodename: pulsar-runner
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /srv/pulsar
detected binary path: …
```

Fixing conda_auto resolving

---

local_env.sh.sample
pulsar/client/client.py
pulsar/client/setup_handler.py
pulsar/manager_endpoint_util.py
pulsar/managers/__init__.py
pulsar/managers/base/__init__.py
pulsar/managers/base/base_drmaa.py
pulsar/managers/base/directory.py
pulsar/managers/queued.py
pulsar/managers/queued_cli.py
pulsar/managers/queued_condor.py
pulsar/managers/queued_drmaa.py
pulsar/managers/queued_drmaa_xsede.py
pulsar/managers/queued_external_drmaa.py
pulsar/managers/unqueued.py
pulsar/managers/util/job_script/DEFAULT_JOB_FILE_TEMPLATE.sh
pulsar/managers/util/job_script/__init__.py

- Properly support `$GALAXY_VIRTUAL_ENV` in Pulsar. This will work if set in the environment or as `<param id="remote_property_galaxy_virtual_env">/path/to/venv</param>` on a Pulsar destination in Galaxy's `job_conf.xml`. And maybe if set in `app.yml`? On a manager??
- Support `$PRESERVE_GALAXY_ENVIRONMENT` so the Galaxy env won't be set up for tools that don't need it.
- Properly (re)activate the Galaxy virtualenv after running the tool command
Galaxy virtualenv reactivation works in Galaxy because the tool command is in a separate file, and so executes in a subshell of the job script, so any environmental changes made for the tool don't propagate back to the job script environment.
With Pulsar, the tool command line is generated with metadata commands on the Galaxy side and passed to …

Remote metadata fixes and enhancements

---

pulsar/client/client.py
pulsar/client/staging/__init__.py
pulsar/client/staging/up.py
pulsar/manager_endpoint_util.py
pulsar/managers/stateful.py
pulsar/web/routes.py

When using remote staging with retries, if a job fails and never writes to its expected output(s), Pulsar will retry output collection on outputs that will never exist, and fail the job once it gives up. This change causes them to be created before the job is executed, mirroring the behavior in Galaxy.

Precreate Galaxy tool outputs on the remote before executing.

---

pulsar/client/job_directory.py
pulsar/client/staging/up.py
test/client_staging_test.py

Fixes the `job directory required for action FileAction[...` error. All of the necessary params are available from the remote server in the job config, and setting the `jobs_directory` param disables querying remote params, so either way we'll know what the job directory is.

Support the remote_transfer file action without setting the jobs_directory destination param

---

README.rst

Old link is giving a 404 error. New link from dannon to new wiki.

Update link for logo image

---

pulsar/client/test/check.py
pulsar/manager_factory.py
pulsar/managers/base/__init__.py
pulsar/managers/base/directory.py
test/integration_test.py

Set with maximum_stream_size in app.yml.
Default to 1MB.
Fixes underlying problem in #151 I think, though doesn't actually do what was requested. I prefer this - is that okay @natefoo?

Add configuration parameter to limit stream size read from disk.

---

pulsar/manager_endpoint_util.py
pulsar/managers/stateful.py
test/integration_test_cli_submit.py
test/integration_test_state.py

For staging, it already worked I think but add a test case to make sure.
For setup problems, we now explicitly raise a message.
Fixes #129 (I think anyway).

Improve message handling if problems occur during job setup/staging.

---

pulsar/manager_endpoint_util.py
pulsar/managers/staging/post.py
pulsar/managers/stateful.py
test/persistence_test.py

- Instead of persisting job metadata for preprocessing - write out metadata for preprocessing and launching.
- Track list of jobs currently being "preprocessed" - not just launched.
- Use the list to attempt to "recover" preprocessing jobs after restart.
- Skip preprocessing complexity all together (extra metadata in the job for instance and this new list) if not preprocessing steps are needed.
- Test case for new behavior.
Should fix #161.

Rework preprocessing job state.

---

Makefile
dev-requirements.txt
docker/coexecutor/Dockerfile
docker/coexecutor/Makefile
pulsar/client/action_mapper.py
pulsar/client/client.py
pulsar/client/manager.py
pulsar/client/staging/__init__.py
pulsar/client/staging/up.py
pulsar/client/test/check.py
pulsar/main.py
pulsar/managers/base/directory.py
pulsar/managers/queued.py
pulsar/managers/unqueued.py
pulsar/managers/util/pykube_util.py
test/client_staging_test.py
test/integration_test.py
test/integration_test_cli_submit.py
test/main_util_test.py
test/manager_coexecution_test.py
test/test_utils.py

Testing for Kubernetes installed with Docker for Mac:
- Run ``make build-coexecutor-container``
- Install and start rabbitmq on the localhost with Homebrew.
- ``PULSAR_TEST_INFRASTRUCTURE_HOST=docker.for.mac.localhost  PULSAR_TEST_FILE_SERVER_HOST=0.0.0.0 PULSAR_RABBIT_MQ_CONNECTION='amqp://guest:guest@localhost:5672//' nosetests test/integration_test.py:ExternalQueueIntegrationTests.test_integration_kubernetes``

Kubernetes Two-Container Pod Staging and Exec

---

docker/coexecutor/Dockerfile
pulsar/client/client.py
pulsar/managers/unqueued.py
test/integration_test.py
test/manager_coexecution_test.py

- Don't hardcode the job ID - it makes Galaxy mapping tricky, seems to be not reason to anyway.
- Don't assume tool execution container has bash.
- Rev to this version of Pulsar.
- Better exception handling related to containers.

Revisions to Kubernetes coexecution pods.

---

.travis.yml
Makefile
dev-requirements.txt
tox.ini

Lint actual artifacts to publish, fail to publish if they don't lint, use twince check instead of deprecated readme package.

Improve readme linting.

---

docs/job_managers.rst

Using queued_drmaa works indeed, but I guess the intention was to use queued_condor here.

using queued_condor

---

.travis.yml
.travis/setup_tests.sh
docker/coexecutor/Dockerfile
docker/coexecutor/Makefile
pulsar/client/client.py
pulsar/client/staging/__init__.py
pulsar/core.py
pulsar/scripts/_conda_init.py
setup.py

Multiple threads working together here despite relatively small changes.
- These changes get extended remote metadata from https://github.com/galaxyproject/galaxy/pull/7058 working.
- These changes are meant to make working with dependency resolution configured from a hierarchical Galaxy config more easy - respect ``dependency_resolution:`` config tag from https://github.com/galaxyproject/galaxy/pull/8152.
- Trying to get more Kubernetes configuration and deployment options working - extended metadata, single container dependency resolution, maybe others....

Handle extended remote metadata.

---

pulsar/managers/queued_condor.py

Preamble: CondorQueueManager handles parameters from the Pulsar config file (app.yml) but ignores parameters submitted from Galaxy.
This PR allows Pulsar to properly handle the HTCondor parameters received from Galaxy:
submit_params variable contains parameters from the JSON received from Galaxy
self.submission_params variable contains parameters from the app.yml file.
In the event of a conflict, the setting on the Pulsar side prevails.

fix parameters submission

---

pulsar/client/client.py
pulsar/managers/unqueued.py
pulsar/managers/util/pykube_util.py

Builds on #220 
Though this is important in its own right - reproducibly fetching the job object from destination parameters in the client was one the challenges needed to track pod status we needed for podIP and doing remote IT jobs this way.

Implement killing k8s jobs.

---

pulsar/managers/queued.py
pulsar/managers/stateful.py
pulsar/messaging/__init__.py

Python 2.6 is listed in setup.py but I guess it's safe to ignore it since it was EoL long time ago. Fixes #224

Use is_alive in favour of isAlive for Python 3.9 compatibility.

---

.travis.yml
Makefile
install_test/common_functions.bash
install_test/test_install.bash
pulsar/client/test/check.py
pulsar/client/transport/__init__.py
pulsar/client/transport/standard.py
pulsar/scripts/config.py
requirements.txt
setup.py
test/client_test.py
test/client_transport_test.py
tox.ini

It's not going to work on 2.7 much longer anyway as galaxy-lib no longer supports 2.7.

Drop Python 2.7 support in standard transport, drop Python 2.7 tests and fix Python 3.7 wheel install test, general test debugging enhancements

---

pulsar/managers/util/condor/__init__.py

This PR fixes the "Exception: cannot use a string pattern on a bytes-like object" into the condor manager with py3.

Fix a unicode issue and polish a bit of variables

---

pulsar/client/config_util.py
pulsar/main.py

Explicitly specify the FullLoader to avoid the warning during the boot-up. 
This is currently (PyYAML 5.1) the default loader called by yaml.load(input) (after issuing the warning).
See [PyYAML-yaml.load(input)-Deprecation](https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation)

fix the PyYAML "load() deprecation" warning

---

pulsar/client/client.py

Otherwise you can only use the `_default_` manager with coexecution pods, and that means you can only use the default AMQP queue/exchange for coexecution runners.

Set --manager when running in coexecution mode and a manager name is set on the client manager.

---

docker/coexecutor/Dockerfile
docker/coexecutor/Makefile

@jmchilton I started updating this before I remembered that I don't actually need to update Pulsar, just Galaxy's pulsar lib. Anyway, since this is still Python 2-based, it's probably not a bad idea to update it. But do you recall why you were using the system python instead of the Conda python?

Update coexecution container Dockerfile for 0.14.1

---

pulsar/client/__init__.py
pulsar/client/staging/__init__.py

Requires a Galaxy piece also. Also we should figure out if there is a clean way to just turn off static, structured outputs in this scenario also.

Send fewer files when doing extended & remote metadata.

---

pulsar/managers/util/job_script/DEFAULT_JOB_FILE_TEMPLATE.sh

I believe `_GALAXY_JOB_HOME_DIR` had not been used in pulsar before (unless a tool explicitly used it). It's probably a good idea to keep this out outside of the `/working` dir, which it seems to be created in currently (see the test that is going to fail in https://github.com/galaxyproject/galaxy/pull/12037/checks?check_run_id=2642104127).

Move $_GALAXY_JOB_HOME_DIR out of /working dir

---

pulsar/client/staging/down.py

When a tool fails it's often not going to create `from_work_dir` outputs. Currently this causes Pulsar to send a `failed` state to Galaxy due to stageout failures, and this makes diagnosing job failure causes much less apparent to the user.
i.e. this change turns this unhelpful message:
into this:
(where "Tool failed for reasons" is the actual error message generated by my very fine failure testing tool).
Fixes #211.

Allow from_work_dir output stage out failure

---

pulsar/client/job_directory.py
pulsar/managers/base/__init__.py

Fixes #239.
I am not sure about what the duplication is for in `client/job_directory.py` and what to do for that case. Also, no idea how we'll get the tool profile handling down to `calculate_path()`, but that is a problem for future Nate?

Support globs in from_work_dir outputs

---

pulsar/client/job_directory.py
pulsar/client/staging/__init__.py
pulsar/client/staging/up.py
pulsar/client/test/check.py
pulsar/managers/base/__init__.py
test/integration_test.py

Pairs with https://github.com/galaxyproject/galaxy/pull/12250 as an alternative approach to https://github.com/galaxyproject/pulsar/pull/260 that allows Galaxy (either at the tool or framework level (for legacy tools)) to override how referenced tool files are found.
This:
- Allows nested tool files like https://github.com/galaxyproject/pulsar/pull/260.
- Allows the Pulsar client to override the tool files transferred via an explicit list (that can be setup a couple different ways in Galaxy in https://github.com/galaxyproject/galaxy/pull/12250.
- Adds an integration test case including with nested files.

Accept description of tool files to transfer from Galaxy.

---

.github/workflows/galaxy_framework.yaml

and remove super-verbose `-s` flag

Run Galaxy framework tests against dev and master branches of Galaxy

---

pulsar/client/client.py
pulsar/client/staging/__init__.py
pulsar/client/staging/down.py
pulsar/client/staging/up.py
pulsar/client/test/check.py
pulsar/manager_endpoint_util.py
pulsar/managers/base/__init__.py
pulsar/managers/staging/__init__.py
pulsar/managers/staging/post.py
pulsar/web/routes.py
setup.cfg
test/client_staging_test.py
test/integration_test.py

A matching Galaxy PR needs to be done after the client is published that records the expected location of the tool provided metadata file and the type.
Matching client update in the integration tests.
https://github.com/galaxyproject/pulsar/pull/269/files#diff-8d13dd3d59bfdedd1272c7a1bd9f3b76f24224ca80a5c1185775c905e250827bR270
Fixes https://github.com/galaxyproject/pulsar/issues/93

Implement dynamic file sources abstraction for parsing files to transfer from galaxy.jsons

---

.github/workflows/pulsar.yaml
tox.ini

Make tox environment structured like gxformat2 and planemo - it is more concise and allow less repetition when adding tasks for multiple Python versions.

Modernize tox.

---

docker/coexecutor/Dockerfile
docker/coexecutor/Makefile
pulsar/client/client.py
pulsar/client/test/check.py
test/integration_test.py

Notes to future John about running the tests.

Update Kubernetes container for latest releases.

---

.github/workflows/pulsar.yaml
mypy.ini
pulsar/client/manager.py
pulsar/web/framework.py
requirements.txt
setup.py
tox.ini

Planemo tests still fail on the py37-install_wheel build, but I don't know enough about those to fix it.
I think these are still good fixes and could probably be merged nonetheless?

Test and mypy fixes. Add support for 3.11

---

app.yml.sample
dev-requirements.txt
mypy.ini
pulsar/client/amqp_exchange.py
pulsar/client/amqp_exchange_factory.py
pulsar/messaging/bind_amqp.py
setup.py

`ConnectionForced` seems very deliberate and may not fix all of https://github.com/galaxyproject/pulsar/issues/316, but a controlled restart of a rabbitmq server results in:
```
Apr 20 09:20:12 gat-24.oz.galaxy.training pulsar[71616]: Exception in thread consume-kill-pyamqp://pulsar_au:********@gat-4.eu.galaxy.training:5671//pulsar/pulsar_au?ssl=1:
Apr 20 09:20:12 gat-24.oz.galaxy.training pulsar[71616]: Traceback (most recent call last):
Apr 20 09:20:12 gat-24.oz.galaxy.training pulsar[71616]:   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Apr 20 09:20:12 gat-24.oz.galaxy.training pulsar[71616]:     self.run()
Apr 20 09:20:12 gat-24.oz.galaxy.training pulsar[71616]:   File "/usr/lib/python3.10/threading.py", line 953, in run
Apr 20 09:20:12 …
```

Allow recovery from rabbitmq restart

---

pulsar/client/amqp_exchange.py

Avoids verbose log messages like
```
2023-04-28 16:07:36,784 WARNI [pulsar.client.amqp_exchange][consume-setup-amqp://guest:********@localhost:5672] Got TimeoutError, will retry: timed out
2023-04-28 16:07:36,784 WARNI [pulsar.client.amqp_exchange][consume-status-amqp://guest:********@localhost:5672] Got TimeoutError, will retry: timed out
2023-04-28 16:07:36,784 WARNI [pulsar.client.amqp_exchange][consume-kill-amqp://guest:********@localhost:5672] Got TimeoutError, will retry: timed out
2023-04-28 16:07:37,578 DEBUG [pulsar.client.amqp_exchange][consume-heartbeat-pulsar__status] AMQP heartbeat thread exiting
2023-04-28 16:07:37,579 DEBUG [pulsar.client.amqp_exchange][consume-heartbeat-pulsar__kill] AMQP heartbeat thread exiting
2023-04-28 16:07:37,579 DEBUG …
```

Catch drain timeout without verbose log message

---

.gitignore
app.yml.sample
docs/configure.rst
pulsar/client/client.py
pulsar/client/staging/up.py
pulsar/core.py
pulsar/manager_endpoint_util.py
pulsar/managers/base/__init__.py
pulsar/user_auth/manager.py
pulsar/user_auth/methods/allow_all.py
pulsar/user_auth/methods/interface.py
pulsar/user_auth/methods/oidc.py
pulsar/user_auth/methods/userlist.py
requirements.txt
setup.py
test/client_staging_test.py
test/manager_test.py
test/persistence_test.py
test/test_utils.py
test/user_authorization_test.py

Allows to configure plugins for user authentication/authorization. Includes methods to authenticate based on OIDC token (see issue https://github.com/galaxyproject/galaxy/issues/15526).
This is a stacked PR after https://github.com/galaxyproject/pulsar/pull/320

User auth plugins

---

requirements.txt

There is a change https://github.com/galaxyproject/galaxy/pull/11393 to the package that fixes cgroup job metric collection.

Update galaxy-job-metrics requirement

---

pulsar/client/amqp_exchange.py

I'd love if this wasn't so broad, but fixes
```
Sep 14 02:50:25 jetstream2.galaxyproject.org pulsar[3746252]: 2023-09-14 02:50:25,143 ERROR [pulsar.client.amqp_exchange][consume-setup-amqp://main_pulsar:********@amqp.galaxyproject.org:5671//main_pulsar?ssl=1] Problem consuming queue, consumer quitting in problematic fashion!
Sep 14 02:50:25 jetstream2.galaxyproject.org pulsar[3746252]: Traceback (most recent call last):
Sep 14 02:50:25 jetstream2.galaxyproject.org pulsar[3746252]:   File "/srv/pulsar/main/venv/lib64/python3.9/site-packages/pulsar/client/amqp_exchange.py", line 143, in consume
Sep 14 02:50:25 jetstream2.galaxyproject.org pulsar[3746252]:     connection.drain_events(timeout=self.__timeout)
Sep 14 02:50:25 jetstream2.galaxyproject.org pulsar[3746252]:   File …
```

Add catchall OSError to recoverable exceptions

---

pulsar/manager_endpoint_util.py

Fixes https://github.com/galaxyproject/pulsar/issues/346

Use unicodify to deal with potential binary contents

---

pulsar/managers/staging/post.py
pulsar/managers/staging/pre.py
pulsar/managers/stateful.py

Mostly fixes #364. Ideally we would also interrupt any running transfers since those could be exceptionally long running and wasteful, but doing so requires interrupting a thread running a non-looping action.
We are probably better off moving those to more properly managed asynchronous tasks (celery, multiprocessing, etc.).
EDIT: Also fixes #353, although not by caring whether it's a 403.

Do not attempt to complete pre- or post-process if jobs are cancelled in the middle of either stage

---

pulsar/web/routes.py
test/wsgi_app_test.py

Currently, there is no endpoint that can be queried to indicate a running pulsar. This makes it difficult for us to add liveness and readiness probes for the pulsar helm chart.

Add health check endpoint

---

docker/kubernetes/Dockerfile

Also switch to Pulsar user, which was accidentally dropped in a previous PR. When running as Pulsar, apptainer also needs the starter-suid binary, which has been included.
xref: https://github.com/galaxyproject/pulsar/pull/395
xref: https://github.com/galaxyproject/pulsar-helm/pull/6

Share docker group between pulsar and dind

---

pulsar/managers/util/tes.py

This PR implements basic authorisation functionality in job submission to TES server.
Job configuration is extended by following options:
```
authorization: "basic"  # Can be "none" or "basic"
basic_auth:
username: "user"
password: "password"
```
Following this approach the OAuth2 authorisation could be implemented, although it requires an implementation of underlying mechanism that would obtain and refresh service tokens from the configured authority.
This PR is dependent on [PR#5](https://github.com/jmchilton/pydantic-tes/pull/5) in [pydantic-tes](https://github.com/jmchilton/pydantic-tes)

BasicAuth for PulsarTesRunner

---

test/integration_test.py
test/test_utils.py

- Read port at which the Pulsar test file server should listen from `PULSAR_TEST_FILE_SERVER_PORT`.
- Make the files endpoint customizable via a new `PULSAR_TEST_INTERNAL_JOB_FILES_URL` variable.
- Use `PULSAR_TEST_FILE_SERVER_HOST` only for the test file server (rather than also using it for the test Pulsar app).
These changes make it possible to expose the files server via port-forwarding (since the files server port is now predictable). This is useful for testing the [upcoming staging delegation](https://github.com/galaxyproject/pulsar/pull/399) with an [external service (e.g. ARC)](https://github.com/galaxyproject/pulsar/pull/401).

Customizable Pulsar test file server port and files endpoint
